version: '3'

services:
  imgproxy:
    image: darthsim/imgproxy:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      IMGPROXY_USE_S3: 'true'
      AWS_ACCESS_KEY_ID: minioroot
      AWS_SECRET_ACCESS_KEY: minioroot
      IMGPROXY_S3_ENDPOINT: http://127.0.0.1:9000
      AWS_REGION: us-east-1
    links:
      - minio

  minio:
    image: quay.io/minio/minio
    volumes:
      - c:\minio\data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioroot
      MINIO_ROOT_PASSWORD: minioroot
    command: server --address ":9000" --console-address ":9090" /data
